[package]
name = "margin"
version = "1.0.0"
description = "Margin: attendance tracker for college students"
edition = "2021"

[lib]
name = "margin_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
